# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Aleksey Kabanov <ak099@mail.ru>, 2018
# ZIzA, 2020
# Темак, 2023
# Victor, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Victor, 2023\n"
"Language-Team: Russian (https://app.transifex.com/calamares/teams/20061/ru/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ru\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Установить загрузчик."

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "Не удалось установить grub, разделы не определены в общем хранилище"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "Ошибка установки загрузчика"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Загрузчик установить не удалось. Команда установки <pre>{!s}</pre> вернула "
"код ошибки {!s}."

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "Не удаётся записать файл конфигурации LXDM"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "Файл конфигурации LXDM {!s} не существует"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "Не удается записать файл конфигурации LightDM"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "Файл конфигурации LightDM {!s} не существует"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "Не удалось настроить LightDM"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "LightDM Greeter не установлен."

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "Не удается записать файл конфигурации SLIM"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "Файл конфигурации SLIM {!s} не существует"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "Для модуля displaymanager не выбраны менеджеры дисплеев."

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Список дисплейных менеджеров пуст или не определен в globalstorage и в "
"displaymanager.conf."

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "Конфигурация дисплейного менеджера не завершена."

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Создание initramfs с помощью dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Не удалось запустить dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Dracut не удалось запустить на целевом объекте с кодом возврата: "
"{return_code}."

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Фиктивная работа python."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Фиктивный шаг python {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "Запись fstab."

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Ошибка конфигурации"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Не определены разделы для использования <pre>{!s}</pre>."

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"Не указана корневая точка монтирования для использования <pre>{!s}</pre>."

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Конфигурация <pre>{!s}</pre> для использования <pre>{!s}</pre> не указана."

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "Настройте GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Установка аппаратных часов."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Настройка mkinitcpio."

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Не определены разделы для <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Настройка initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Настройка языка."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Создание initramfs с помощью mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Не удалось запустить mkinitfs на целевой объект"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Код выхода {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Монтирование разделов."

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "Внутренняя ошибка при монтировании наборов данных zfs"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "Не удалось импортировать zpool"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "Не удалось разблокировать zpool"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "Не удалось задать точку монтирования zfs"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "Ошибка монтирования zfs"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Сохранение сетевых настроек."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Настройка службы OpenRC dmcrypt."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Установить пакеты."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Обработка пакетов (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Установка одного пакета."
msgstr[1] "Установка %(num)d пакетов."
msgstr[2] "Установка %(num)d пакетов."
msgstr[3] "Установка %(num)d пакетов."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Удаление одного пакета."
msgstr[1] "Удаление %(num)d пакетов."
msgstr[2] "Удаление %(num)d пакетов."
msgstr[3] "Удаление %(num)d пакетов."

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "Ошибка менеджера пакетов"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Менеджер пакетов не смог подготовить обновления. Команда <pre>{!s}</pre> "
"вернула код ошибки {!s}."

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Менеджер пакетов не смог обновить систему. Команда <pre>{!s}</pre> вернула "
"код ошибки {!s}."

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Менеджер пакетов не смог внести изменения в установленную систему. Команда "
"<pre>{!s}</pre> вернула код ошибки {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Настроить тему Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Установка данных."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Настройка служб OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Невозможно добавить службу {name!s} на уровень выполнения {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Невозможно удалить службу {name!s} с уровня выполнения {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Неизвестное действие службы <code>{arg!s}</code> для службы {name!s} на "
"уровне выполнения {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Не удается изменить службу"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"Вызов <code>rc-update {arg!s}</code> в chroot вернул код ошибки {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Целевой уровень выполнения не существует"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Путь уровня выполнения {level!s} — <code>{path!s}</code>, которого не "
"существует."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Целевой службы не существует"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Путь к сервису {name!s} — <code>{path!s}</code>, который не существует."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Настройка юнитов systemd"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Не удается изменить юнит"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Не удается {_action!s} юнит systemd <code>{name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Наполнение файловой системы."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "Ошибка выполнения rsync с кодом {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Извлечение образа {}/{}, файл {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "Начало извлечения {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Не удалось распаковать образ \"{}\""

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Нет точки монтирования для раздела root"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage не содержит ключа \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Неверная точка монтирования для корневого раздела "

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint — это \"{}\", которого не существует."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Неверная конфигурация unpackfs"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Нет информации о конфигурации."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "Файловая система для \"{}\" ({}) не поддерживается вашим текущим ядром"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "Исходная файловая система \"{}\" не существует"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Не удалось найти unsquashfs, убедитесь, что у вас установлен пакет squashfs-"
"tools."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Назначение \"{}\" в целевой системе не является каталогом"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Копирование сгенерированного zfs id хоста."
