# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Jiri Grönroos <jiri.gronroos@iki.fi>, 2022
# Kimmo Kujansuu <mrkujansuu@gmail.com>, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Kimmo Kujansuu <mrkujansuu@gmail.com>, 2023\n"
"Language-Team: Finnish (Finland) (https://app.transifex.com/calamares/teams/20061/fi_FI/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fi_FI\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Asenna käynnistyslatain."

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Grubin asennus epäonnistui, yleisessä levytilassa ei ole määritetty osioita"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "Käynnistyslataimen asennusvirhe"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Käynnistyslatainta ei voitu asentaa. Asennuskomento <pre>{!s}</pre> palautti"
" virhekoodin {!s}."

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "LXDM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "LightDM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "LightDM-määritysvirhe"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "LightDM:ää ei ole asennettu."

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "SLIM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "Displaymanager-moduulia varten ei ole valittu näytönhallintaa."

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Luettelo on tyhjä tai määrittelemätön, sekä globalstorage, että "
"displaymanager.conf tiedostossa."

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "Näytönhallinnan kokoonpano oli puutteellinen"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Luodaan initramfs:ää dracutilla."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Dracutin suoritus epäonnistui"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr "Dracutin suoritus epäonnistui. Kohteen palautuskoodi: {return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Dummy-mallinen python-työ."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Dummy-mallinen python-vaihe {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "Kirjoitetaan fstabiin."

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Määritysvirhe"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Osioita ei ole määritetty käytettäväksi kohteelle <pre>{!s}</pre> ."

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Kohteelle <pre>{!s}</pre> ei ole annettu juuriliitospistettä."

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"\"<pre>{!s}</pre>\"-määritystä ei ole annettu käytettäväksi kohteelle "
"<pre>{!s}</pre>."

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "Määritä GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Asetetaan laitteiston kelloa."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Määritetään mkinitcpio."

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Osiota ei ole määritetty käytettäväksi <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Ei root liitospistettä käytettäväksi <pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Määritetään initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Määritetään maa-asetuksia."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Luodaan initramfs mkinitfs:llä."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "mkinitfs:n suorittaminen kohteessa epäonnistui"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Poistumiskoodi oli {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Liitetään osioita."

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "Sisäinen virhe liitettäessä zfs-tietojoukkoa"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "Zpoolin tuonti epäonnistui"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "Zpoolin lukituksen avaaminen epäonnistui"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "Määritys zfs-liitospisteen epäonnistui"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "zfs-liitosvirhe"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Tallennetaan verkon määrityksiä."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Määritetään OpenRC:n dmcrypt-palvelua."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Asenna paketit."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Käsitellään paketteja (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Asennetaan yhtä pakettia."
msgstr[1] "Asennetaan %(num)d pakettia."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Poistetaan yhtä pakettia."
msgstr[1] "Poistetaan %(num)d pakettia."

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "Paketinhallinnan virhe"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Paketinhallinta ei voinut valmistella päivityksiä. Komento <pre>{!s}</pre> "
"palautti virhekoodin {!s}."

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Paketinhallinta ei voinut päivittää järjestelmää. Komento <pre>{!s}</pre> "
"palautti virhekoodin {!s}."

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Paketinhallinta ei voinut tehdä muutoksia asennettuun järjestelmään. Komento"
" <pre>{!s}</pre> palautti virhekoodin {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Määritä Plymouthin teema"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Asennetaan tietoja."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Määritä OpenRC-palvelut"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Palvelua {name!s} ei voi lisätä suorituksen tasolle {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Ei voi poistaa palvelua {name!s} suorituksen tasolla {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Tuntematon  huoltotoiminto<code>{arg!s}</code> palvelun {name!s} "
"palvelutasolle  {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Palvelua ei voi muokata"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> palautti chrootissa virhekoodin {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Kohteen ajotasoa ei ole olemassa"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "Ajotason polku {level!s} on <code>{path!s}</code>, jota ei ole."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Kohdepalvelua ei ole"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Palvelun polku {name!s} on <code>{path!s}</code>,  jota ei ole olemassa."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Määritä systemd-yksiköt"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Yksikköä ei voi muokata"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"<code>systemctl {_action!s}</code> chrootin kutsu palautti virhekoodin "
"{_exit_code!s}."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Ei voi {_action!s} systemd yksiköt <code>{_name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Täytetään tiedostojärjestelmiä."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync epäonnistui virhekoodilla {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Puretaan levykuvaa {}/{}, tiedosto {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "Pakkauksen purkaminen alkaa {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Levykuvan\"{}\" purkaminen epäonnistui"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Ei liitospistettä juuriosiolle"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage ei sisällä \"rootMountPoint\"-avainta."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Virheellinen liitospiste juuriosiolle"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint on \"{}\", jota ei ole olemassa."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Virheellinen unpacckfs-määritys"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Määritystietoja ei ole."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "Tiedostojärjestelmä \"{}\" ({}) ei tue käytössä olevaa kerneliä"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "Lähdetiedostojärjestelmää \"{}\" ei ole olemassa"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Unsquashfs-tiedostoja ei löytynyt, varmista, että paketti squashfs-tools on "
"asennettu."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Kohdejärjestelmän kohde \"{}\"  ei ole hakemisto"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Kopioidaan zfs:n luomaa hostid:tä."
