# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Adriaan de Groot <groot@kde.org>, 2018
# Balázs Meskó <meskobalazs@mailbox.org>, 2018
# miku84, 2019
# Lajos Pasztor <mrlajos@gmail.com>, 2019
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-27 11:18+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Lajos Pasztor <mrlajos@gmail.com>, 2019\n"
"Language-Team: Hungarian (https://www.transifex.com/calamares/teams/20061/hu/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Csomagok telepítése."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Csomagok feldolgozása (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Egy csomag telepítése."
msgstr[1] "%(num)d csomag telepítése."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Egy csomag eltávolítása."
msgstr[1] "%(num)d csomag eltávolítása."

#: src/modules/packages/main.py:725 src/modules/packages/main.py:737
#: src/modules/packages/main.py:765
msgid "Package Manager error"
msgstr ""

#: src/modules/packages/main.py:726
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""

#: src/modules/packages/main.py:738
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""

#: src/modules/packages/main.py:766
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Hálózati konfiguráció mentése."

#: src/modules/networkcfg/main.py:105 src/modules/initcpiocfg/main.py:235
#: src/modules/initcpiocfg/main.py:239 src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:229 src/modules/fstab/main.py:394
#: src/modules/fstab/main.py:400 src/modules/fstab/main.py:428
#: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
#: src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Konfigurációs hiba"

#: src/modules/networkcfg/main.py:106 src/modules/initcpiocfg/main.py:240
#: src/modules/openrcdmcryptcfg/main.py:77 src/modules/localecfg/main.py:141
#: src/modules/fstab/main.py:401 src/modules/initramfscfg/main.py:90
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Nincs root csatolási pont megadva a <pre>{!s}</pre> használatához."

#: src/modules/initcpiocfg/main.py:28
msgid "Configuring mkinitcpio."
msgstr "mkinitcpio konfigurálása."

#: src/modules/initcpiocfg/main.py:236 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/mount/main.py:230 src/modules/fstab/main.py:395
#: src/modules/initramfscfg/main.py:86 src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Nincsenek partíciók meghatározva a <pre>{!s}</pre> használatához."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr ""

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr ""

#: src/modules/mkinitfs/main.py:50 src/modules/dracut/main.py:50
msgid "The exit code was {}"
msgstr "A kilépési kód {} volt."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt szolgáltatás konfigurálása."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Fájlrendszerek betöltése."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "az rsync elhalt a(z) {} hibakóddal"

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr ""

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr ""

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "\"{}\" kép kicsomagolása nem sikerült"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Nincs betöltési pont a root partíciónál"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr ""

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Rossz betöltési pont a root partíciónál"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr ""

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr ""

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr ""

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "A forrás fájlrendszer \"{}\" nem létezik"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Az elérés \"{}\" nem létező könyvtár a cél rendszerben"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd services"
msgstr "systemd szolgáltatások beállítása"

#: src/modules/services-systemd/main.py:59
#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "a szolgáltatást nem lehet módosítani"

#: src/modules/services-systemd/main.py:60
msgid ""
"<code>systemctl {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>systemctl {arg!s}</code> hívás a chroot-ban hibakódot okozott {num!s}."

#: src/modules/services-systemd/main.py:63
#: src/modules/services-systemd/main.py:69
msgid "Cannot enable systemd service <code>{name!s}</code>."
msgstr ""
"Nem sikerült a systemd szolgáltatást engedélyezni: <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:65
msgid "Cannot enable systemd target <code>{name!s}</code>."
msgstr "Nem sikerült a systemd célt engedélyezni: <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:67
msgid "Cannot enable systemd timer <code>{name!s}</code>."
msgstr ""

#: src/modules/services-systemd/main.py:71
msgid "Cannot disable systemd target <code>{name!s}</code>."
msgstr "Nem sikerült a systemd cél <code>{name!s}</code> letiltása."

#: src/modules/services-systemd/main.py:73
msgid "Cannot mask systemd unit <code>{name!s}</code>."
msgstr "Nem maszkolható systemd egység: <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:75
msgid ""
"Unknown systemd commands <code>{command!s}</code> and "
"<code>{suffix!s}</code> for unit {name!s}."
msgstr ""
"Ismeretlen systemd parancsok <code>{command!s}</code> és "
"<code>{suffix!s}</code> a {name!s} egységhez. "

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Hamis Python feladat."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Hamis {}. Python lépés"

#: src/modules/bootloader/main.py:43
msgid "Install bootloader."
msgstr "Rendszerbetöltő telepítése."

#: src/modules/bootloader/main.py:614
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""

#: src/modules/bootloader/main.py:782
msgid "Bootloader installation error"
msgstr ""

#: src/modules/bootloader/main.py:783
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "nyelvi értékek konfigurálása."

#: src/modules/mount/main.py:42
msgid "Mounting partitions."
msgstr "Partíciók csatolása."

#: src/modules/mount/main.py:88 src/modules/mount/main.py:124
msgid "Internal error mounting zfs datasets"
msgstr ""

#: src/modules/mount/main.py:100
msgid "Failed to import zpool"
msgstr ""

#: src/modules/mount/main.py:116
msgid "Failed to unlock zpool"
msgstr ""

#: src/modules/mount/main.py:133 src/modules/mount/main.py:138
msgid "Failed to set zfs mountpoint"
msgstr ""

#: src/modules/mount/main.py:253
msgid "zfs mounting error"
msgstr ""

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouth téma beállítása"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "fstab írása."

#: src/modules/fstab/main.py:429
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRC szolgáltatások beállítása"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Nem lehet  {name!s} szolgáltatást hozzáadni a run-level {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Nem lehet törölni a {name!s} szolgáltatást a {level!s} futás-szintből"

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Ismeretlen service-action <code>{arg!s}</code> a szolgáltatáshoz {name!s} in"
" run-level {level!s}."

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> hívás a chroot-ban hibakódot adott: {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "A cél futási szint nem létezik"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"A futási-szint elérési útja {level!s} ami <code>{path!s}</code>, nem "
"létezik."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "A cél szolgáltatás nem létezik"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"A szolgáltatás {name!s} elérési útja <code>{path!s}</code>, nem létezik."

#: src/modules/dracut/main.py:27
msgid "Creating initramfs with dracut."
msgstr "initramfs létrehozása ezzel: dracut."

#: src/modules/dracut/main.py:49
msgid "Failed to run dracut on the target"
msgstr "dracut futtatása nem sikerült a célon."

#: src/modules/grubcfg/main.py:28
msgid "Configure GRUB."
msgstr "GRUB konfigurálása."

#: src/modules/displaymanager/main.py:524
msgid "Cannot write KDM configuration file"
msgstr "A KDM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:525
msgid "KDM config file {!s} does not exist"
msgstr "A(z) {!s} KDM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:586
msgid "Cannot write LXDM configuration file"
msgstr "Az LXDM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:587
msgid "LXDM config file {!s} does not exist"
msgstr "A(z) {!s} LXDM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:670
msgid "Cannot write LightDM configuration file"
msgstr "A LightDM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:671
msgid "LightDM config file {!s} does not exist"
msgstr "A(z) {!s} LightDM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:745
msgid "Cannot configure LightDM"
msgstr "A LightDM nem állítható be"

#: src/modules/displaymanager/main.py:746
msgid "No LightDM greeter installed."
msgstr "Nincs LightDM üdvözlő telepítve."

#: src/modules/displaymanager/main.py:777
msgid "Cannot write SLIM configuration file"
msgstr "A SLIM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:778
msgid "SLIM config file {!s} does not exist"
msgstr "A(z) {!s} SLIM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:992
msgid "No display managers selected for the displaymanager module."
msgstr "Nincs kijelzőkezelő kiválasztva a kijelzőkezelő modulhoz."

#: src/modules/displaymanager/main.py:993
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""

#: src/modules/displaymanager/main.py:1075
msgid "Display manager configuration was incomplete"
msgstr "A kijelzőkezelő konfigurációja hiányos volt"

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "initramfs konfigurálása."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Rendszeridő beállítása."

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Adatok telepítése."
